name: Streamlit Keep-Alive

on:
  schedule:
    - cron: "0 */7 * * *" # Runs every 10 hours
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Push empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keep Streamlit app awake"
          git push
